name: lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run lint --if-present