name: Release and Publish

on:
  push:
    branches:
    - main

jobs:
  release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install the dependencies
        run: npm install

      - name: Install vsce
        run: npm install -g vsce

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: npm run semantic-release

      - name: Publish
        run: vsce publish -p $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}